---
- name: "Add PodMan Repository Key"
  ansible.builtin.apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_{{ ansible_distribution_major_version }}/Release.ke"
    state: "present"

- name: "Add PodMan Repository"
  ansible.builtin.apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_{{ ansible_distribution_major_version }}/ /"
    state: "present"
    filename: "podman"

- name: "Install Debian Dependencies for Podman"
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: "present"
    update_cache: true

- name: "Configure SysCtl kernel.unprivileged_userns_clone"
  ansible.posix.sysctl:
    name: "kernel.unprivileged_userns_clone"
    value: "1"
    state: "present"

- name: "Configure Podman"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    owner: "{{ template.owner | default('root') }}"
    group: "{{ template.group | default('root') }}"
    mode: "{{ template.mode | default('0644') }}"
  loop:
    - src: "etc/containers/registries.conf.j2"
      dest: "/etc/containers/registries.conf"
    - src: "etc/cni/net.d/87-podman-bridge.conflist.j2"
      dest: "/etc/cni/net.d/87-podman-bridge.conflist"
  loop_control:
    loop_var: template
    label: "{{ template.src }}"
  notify: "Restart Podman"
