# role: wireguard
---
- name: "Install Wireguard"
  ansible.builtin.include_tasks: install_wireguard.yml
  args:
    apply:
      become: true
      tags:
        - pan
  when:
    - "network is defined"
    - "network.pan is defined"
  tags:
    - pan

- name: "Configure Monitoring Checks"
  ansible.builtin.include_tasks: configure_icingacheck.yml
  args:
    apply:
      become: true
      tags:
        - pan
  when:
    - "wireguard_icinga_check | bool"
    - "network is defined"
    - "network.pan is defined"
  tags:
    - pan

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - pan
