---
- name: "Remove old Firewall files"
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: "absent"
  loop:
    - path: "/etc/network/firewall/filter.v4.d/1-chain-docker.v4"
    - path: "/etc/network/firewall/filter.v6.d/1-chain-docker.v6"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"

- name: "Configure Firewall for Docker"
  ansible.builtin.template:
    src: "firewall/{{ template.name }}.j2"
    dest: "/etc/network/firewall/{{ template.dest }}/{{ template.name }}"
    owner: "root"
    group: "root"
    mode: "0600"
  loop:
    - name: "01-chain-docker.v4"
      dest: "filter.v4.d"
    - name: "01-chain-docker.v6"
      dest: "filter.v6.d"
    - name: "20-filter-docker.v4"
      dest: "filter.v4.d"
    - name: "20-filter-docker.v6"
      dest: "filter.v6.d"
    - name: "95-filter-docker.v4"
      dest: "filter.v4.d"
    - name: "95-filter-docker.v6"
      dest: "filter.v6.d"
  loop_control:
    loop_var: template
    label: "{{ template.name }}"
  notify: "Restart Firewall"
