---
- name: "Define primary GlusterFS Server for VMs with Hosts"
  ansible.builtin.set_fact:
    gluster_master: "{{ infrastructure.parent }}"
  when:
    - "infrastructure.parent != 'master'"

- name: "Define primary GlusterFS Server for VMs without Hosts"
  ansible.builtin.set_fact:
    gluster_master: "{{ groups['gluster'] | sort | first }}"
  when: "infrastructure.parent == 'master'"

- name: "Define the list of servers"
  ansible.builtin.set_fact:
    gluster_servers: "{{ groups['gluster'] | difference(gluster_master) | join(',') }}"

- name: "Read Plugin list"
  ansible.builtin.command: "docker plugin ls"
  register: docker_plugins
  changed_when: false

- name: "Install GlusterFS Plugin"
  when:
    - "'gv2' not in docker_plugins.stdout"
  block:
    - name: "Install GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin install --alias gv2 trajano/glusterfs-volume-plugin --grant-all-permissions --disable"
      register: docker_plugin_gv2_install
      changed_when: "'Installed' in docker_plugin_gv2_install.stdout"
      ignore_errors: true

    - name: "Configure GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin set gv2 SERVERS={{ gluster_servers }}"
      register: docker_plugin_gv2_setup
      changed_when: "docker_plugin_gv2_setup.rc == 0"

    - name: "Configure GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin enable gv2"
      register: docker_plugin_gv2_enable
      changed_when: "docker_plugin_gv2_enable.rc == 0"
