---
- name: "Restart NTP"
  become: true
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: "restarted"
  ignore_errors: true
  when: "ntp_enabled | bool"

- name: "Restart Fail2Ban"
  become: true
  ansible.builtin.service:
    name: "fail2ban"
    state: "restarted"
    enabled: true
  ignore_errors: true
