---
dependencies:
  - role: acoby.collection.icinga_agent

galaxy_info:
  namespace: acoby
  role_name: pan
  author: Thoralf Rickert-Wendt
  description: A common role for all system to use Wireguard VPN
  company: Acoby GmbH
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - system
    - vpn
    - networking
    - wireguard
