---
bind_default:
  packages:
    - bridge-utils
    - bind9
    - python3-pip
    - python3-dev
    - python3-virtualenv
    - python3-requests
    - python3-pexpect
    - build-essential
    - ethtool
  path: "/etc/bind"
