---
- name: "Install Firewall dependency"
  ansible.builtin.include_tasks: configure.yml
  args:
    apply:
      become: true
      tags:
        - firewall
  when:
    - "hardware.type is not defined or hardware.type != 'physical'"
  tags:
    - firewall
