---
- name: "Assign common role to all hosts"
  hosts: "all"
  tasks:
    - name: "Assign common role"
      ansible.builtin.include_role:
        name: "acoby.collection.common"

- name: "Assign sandbox role to all vms"
  hosts: "vms"
  tasks:
    - name: "Assign sandbox role"
      ansible.builtin.include_role:
        name: "acoby.collection.sandbox"
