---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance1
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/lib/containerd"
    tmpfs:
      - "/run"
      - "/tmp"
  - name: instance2
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/lib/containerd"
    tmpfs:
      - "/run"
      - "/tmp"
  - name: server1
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/lib/containerd"
    tmpfs:
      - "/run"
      - "/tmp"

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      hosts: inventory.yml

verifier:
  name: ansible
