---
- name: "Restart Journald"
  become: true
  ansible.builtin.service:
    name: "systemd-journald"
    state: "restarted"
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Restart Fail2Ban"
  become: true
  ansible.builtin.service:
    name: "fail2ban"
    state: "restarted"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Restart SSH"
  become: true
  ansible.builtin.service:
    name: "sshd"
    state: "restarted"
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Restart Firewall"
  become: true
  ansible.builtin.systemd:
    name: "firewall.service"
    state: "restarted"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Restart Icinga2"
  become: true
  ansible.builtin.service:
    name: "icinga2"
    state: "restarted"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Start Wireguard"
  become: true
  ansible.builtin.systemd:
    name: "wg-quick@{{ network.pan.interface }}"
    state: "started"
    enabled: true
    daemon_reload: true
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Restart Wireguard"
  become: true
  ansible.builtin.systemd:
    name: "wg-quick@{{ network.pan.interface }}"
    state: "restarted"
  ignore_errors: "{{ inventory.id is not defined }}"
