---
- name: "Configure Icinga2 Services"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    owner: "{{ template.owner | default('nagios') }}"
    group: "{{ template.group | default('nagios') }}"
    mode: "{{ template.mode | default('0440') }}"
  loop:
    - src: "constants.conf.j2"
      dest: "/etc/icinga2/constants.conf"
      mode: "0440"
    - src: "conf.d/hosts.conf.j2"
      dest: "/etc/icinga2/conf.d/hosts.conf"
    - src: "conf.d/services.conf.j2"
      dest: "/etc/icinga2/conf.d/services.conf"
    - src: "conf.d/users.conf.j2"
      dest: "/etc/icinga2/conf.d/users.conf"
    - src: "conf.d/commands.conf.j2"
      dest: "/etc/icinga2/conf.d/commands.conf"
    - src: "conf.d/timeperiods.conf.j2"
      dest: "/etc/icinga2/conf.d/timeperiods.conf"
    - src: "conf.d/notifications.conf.j2"
      dest: "/etc/icinga2/conf.d/notifications.conf"
    - src: "conf.d/templates.conf.j2"
      dest: "/etc/icinga2/conf.d/templates.conf"
    - src: "mail.rc.j2"
      dest: "/var/lib/nagios/.mailrc"
    - src: "scripts/rocketchat-host-notification.sh.j2"
      dest: "/etc/icinga2/scripts/rocketchat-host-notification.sh"
      mode: "0550"
    - src: "scripts/rocketchat-service-notification.sh.j2"
      dest: "/etc/icinga2/scripts/rocketchat-service-notification.sh"
      mode: "0550"
    - src: "scripts/acoby-host-notification.sh.j2"
      dest: "/etc/icinga2/scripts/acoby-host-notification.sh"
      mode: "0550"
    - src: "scripts/acoby-service-notification.sh.j2"
      dest: "/etc/icinga2/scripts/acoby-service-notification.sh"
      mode: "0550"
    - src: "scripts/mail-service-notification.sh.j2"
      dest: "/etc/icinga2/scripts/mail-service-notification.sh"
      mode: "0550"
    - src: "scripts/mail-service-notification.sh.j2"
      dest: "/etc/icinga2/scripts/mail-service-notification.sh"
      mode: "0550"
  loop_control:
    loop_var: template
  notify: "Restart Icinga2"

- name: "Copy custom acoby check scripts"
  ansible.builtin.copy:
    src: "{{ file.source }}"
    dest: "{{ file.destination }}"
    owner: "{{ file.owner | default('root') }}"
    group: "{{ file.group | default('root') }}"
    mode: "{{ file.mode | default('0755') }}"
  loop:
    - source: "check_cpu"
      destination: "/usr/lib/nagios/plugins/check_cpu"
      target: "linux"
    - source: "check_eth"
      destination: "/usr/lib/nagios/plugins/check_eth"
      target: "linux"
    - source: "check_glusterfs"
      destination: "/usr/lib/nagios/plugins/check_glusterfs"
      target: "gluster"
    - source: "check_iostat"
      destination: "/usr/lib/nagios/plugins/check_iostat"
      target: "linux"
    - source: "check_iptables"
      destination: "/usr/lib/nagios/plugins/check_iptables"
      target: "linux"
    - source: "check_md_stat"
      destination: "/usr/lib/nagios/plugins/check_md_stat"
      target: "proxmox"
    - source: "check_mountpoint"
      destination: "/usr/lib/nagios/plugins/check_mountpoint"
      target: "linux"
    - source: "check_nobod"
      destination: "/usr/lib/nagios/plugins/check_nobod"
      target: "linux"
    - source: "check_proxysql"
      destination: "/usr/lib/nagios/plugins/check_proxysql"
      target: "service_docker_proxysql"
    - source: "check_pve"
      destination: "/usr/lib/nagios/plugins/check_pve"
      target: "proxmox"
    - source: "check_running_kernel"
      destination: "/usr/lib/nagios/plugins/check_running_kernel"
      target: "linux"
    - source: "check_syncoid"
      destination: "/usr/lib/nagios/plugins/check_syncoid"
      target: "storage"
    - source: "check_temp"
      destination: "/usr/lib/nagios/plugins/check_temp"
      target: "linux"
    - source: "check_zpool"
      destination: "/usr/lib/nagios/plugins/check_zpool"
      target: "storage"
    - source: "check_zpool_scrub"
      destination: "/usr/lib/nagios/plugins/check_zpool_scrub"
      target: "storage"
    - source: "sudoers"
      destination: "/etc/sudoers.d/90-icinga-user"
      mode: "0440"
      target: "linux"
  loop_control:
    loop_var: file
  when:
    - "file.target in group_names"

- name: "Create SystemD Config Dir"
  ansible.builtin.file:
    path: "/etc/systemd/system/icinga2.service.d"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Override System Limits for Icinga"
  ansible.builtin.template:
    src: "systemctl/limits.conf.j2"
    dest: "/etc/systemd/system/icinga2.service.d/limits.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "_monitoring_systemd_limits"

- name: "Reload Systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  ignore_errors: "inventory.id is not defined"
  when: "_monitoring_systemd_limits.changed"

- name: "Override System Defaults for Icinga"
  ansible.builtin.template:
    src: "systemctl/default.j2"
    dest: "/etc/default/icinga2"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Add Ping Checks"
  ansible.builtin.template:
    src: "conf.d/check_ping.conf.j2"
    dest: "/etc/icinga2/conf.d/check_ping.conf"
    owner: "nagios"
    group: "nagios"
    mode: 0440
  when: "monitor is defined and monitor.check.ping is defined"
