---
- name: "Add Icinga2 Repository Key"
  ansible.builtin.apt_key:
    url: "https://packages.icinga.com/icinga.key"
    state: "present"

- name: "Add Icinga2 Repository"
  ansible.builtin.apt_repository:
    repo: "deb http://packages.icinga.com/debian icinga-{{ ansible_distribution_release }} main"
    state: "present"
    filename: "icinga"

- name: "Update Repositories cache and install 'icinga2' package"
  ansible.builtin.apt:
    name:
      - "icinga2"
      - "monitoring-plugins-basic"
      - "s-nail"
      - "nagios-plugins-contrib"
      - "binutils"
      - "libmonitoring-plugin-perl"
      - "sysstat"
      - "bc"
      - "lz4"
      - "lzop"
    update_cache: true

- name: "Clean up Configfiles"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/etc/icinga2/conf.d/apt.conf"
    - "/etc/icinga2/zones.conf.orig"
    - "/etc/icinga2/constants.conf.orig"
    - "/etc/icinga2/scripts/mail-host-notification.sh.dpkg-dist"
    - "/etc/icinga2/scripts/mail-service-notification.sh.dpkg-dist"
