# role: icinga2 standalone
---
- name: "Install Icinga2 packages"
  ansible.builtin.include_tasks: install.yml

- name: "Configure Icinga2 agent settings"
  ansible.builtin.include_tasks: configure.yml

- name: "Configure Icinga2 Zones"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('nagios') }}"
    group: "{{ item.group | default('nagios') }}"
    mode: "{{ item.mode | default('0440') }}"
  with_items:
    - src: "zones.conf.j2"
      dest: "/etc/icinga2/zones.conf"

- name: "Start Icinga2 Service"
  ansible.builtin.service:
    name: "icinga2"
    state: "started"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"
