---
- name: "Verify Mandatory fields"
  ansible.builtin.assert:
    that:
      - "monitor_domain is defined"
    fail_msg: "At least one value for monitoring role is not defined (monitor_configfilename)"

- name: "Set some defaults"
  ansible.builtin.set_fact:
    monitor_configfilename: "{{ 'httpcheck_' + monitor_domain + '.conf' }}"

- name: "Remove Monitoring of Virtualhost for {{ monitor_domain }}"
  ansible.builtin.file:
    path: "/etc/icinga2/conf.d/{{ monitor_configfilename }}"
    state: absent
  register: icinga2template

- name: "Reload Icinga2 Service"
  ansible.builtin.service:
    name: icinga2
    state: reloaded
  when: icinga2template.changed
  tags:
    - icinga2-reconfigure

- name: "Reset defaults"
  ansible.builtin.set_fact:
    monitor_configfilename:
