---
- name: "Enumerate all cluster hosts within the hosts file"
  ansible.builtin.blockinfile:
    dest: "/etc/hosts"
    marker: "# {mark} ANSIBLE MANAGED: Gluster Cluster Hosts"
    content: "\
      {% for host in groups['gluster'] %}\
      {% if network.lan is defined %}{{ hostvars[host].network.gfs.lan.ipv4 }}{% else %}{{ hostvars[host].network.gfs.wan.ipv4 }}{% endif %} {{ hostvars[host].network.gfs.fqdn }}

      {% endfor %}"

- name: "Define primary GlusterFS Server for VMs with Hosts"
  ansible.builtin.set_fact:
    gluster_master: "{{ infrastructure.parent }}"
  when:
    - "infrastructure.parent != 'master'"

- name: "Define primary GlusterFS Server for VMs without Hosts"
  ansible.builtin.set_fact:
    gluster_master: "{{ groups['gluster'] | sort | first }}"
  when: "infrastructure.parent == 'master'"

- name: "Define the list of servers"
  ansible.builtin.set_fact:
    gluster_servers: "{{ groups['gluster'] | difference(gluster_master) | join(',') }}"

- name: "Install GlusterFS Client"
  ansible.builtin.apt:
    name:
      - "glusterfs-client"
    state: "present"

- name: "Add Gluster Mount Point to /etc/fstab"
  ansible.posix.mount:
    src: "{{ hostvars[gluster_master].network.gfs.fqdn }}:/{{ gfs_vol.volume }}/storage"
    path: "{{ gfs_vol.mountpoint }}"
    fstype: "glusterfs"
    opts: "defaults,_netdev"
    state: "mounted"
  loop: "{{ gfs_mount | default([]) }}"
  loop_control:
    loop_var: gfs_vol
    label: "{{ gfs_vol.volume }}"

- name: "Read Plugin list"
  ansible.builtin.command: "docker plugin ls"
  register: docker_plugins
  changed_when: false

- name: "Install GlusterFS Plugin"
  when:
    - "'gv2' not in docker_plugins.stdout"
  block:
    - name: "Install GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin install --alias gv2 trajano/glusterfs-volume-plugin --grant-all-permissions --disable"
      register: docker_plugin_gv2_install
      changed_when: "'Installed' in docker_plugin_gv2_install.stdout"
      failed_when: false
      ignore_errors: true

    - name: "Configure GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin set gv2 SERVERS={{ gluster_servers }}"
      register: docker_plugin_gv2_setup
      changed_when: "docker_plugin_gv2_setup.rc == 0"

    - name: "Configure GlusterFS Docker Plugin"
      ansible.builtin.command: "docker plugin enable gv2"
      register: docker_plugin_gv2_enable
      changed_when: "docker_plugin_gv2_enable.rc == 0"
