---
- name: "Configure Icinga Agent"
  ansible.builtin.include_tasks: configure.yml

- name: "Start Icinga2 Service"
  ansible.builtin.service:
    name: "icinga2"
    state: "started"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Mark Icinga2 instance as managed"
  ansible.builtin.lineinfile:
    path: "/etc/icinga2/.managed"
    create: true
    regex: "^ansible"
    line: "ansible managed"
    owner: "root"
    group: "root"
    mode: "0644"
