---
- name: "Uninstall other firewall alternatives"
  ansible.builtin.apt:
    name:
      - "ufw"
      - "firewalld"
    state: "absent"

- name: "Disable iptables-persistent"
  ansible.builtin.systemd:
    name: "netfilter-persistent.service"
    state: "stopped"
    enabled: false
  ignore_errors: "{{ inventory.id is not defined }}"

- name: "Check if old firewall-init script still exists"
  ansible.builtin.stat:
    path: "/etc/systemd/system/multi-user.target.wants/firewall-init.service"
  register: _firewall_init_service

- name: "Disable old Firewall Service"
  become: true
  ansible.builtin.systemd:
    name: "firewall-init.service"
    state: "stopped"
    enabled: false
  ignore_errors: "{{ inventory.id is not defined }}"
  when:
    - "_firewall_init_service.stat.exists"

- name: "Remove iptables-persistent files"
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: "absent"
  loop:
    - path: "/etc/iptables/rules.v4"
    - path: "/etc/iptables/rules.v6"
    - path: "/etc/network/firewall/init.sh"
    - path: "/etc/network/firewall/rules.sh"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"

- name: "Setup Firewall directories"
  ansible.builtin.file:
    path: "{{ directory.path }}"
    owner: "{{ directory.owner | default('root') }}"
    group: "{{ directory.group | default('root') }}"
    mode: "{{ directory.mode | default('0700') }}"
    state: "directory"
  loop:
    - path: "/etc/network/firewall/"
    - path: "/etc/network/firewall/filter.v4.d"
    - path: "/etc/network/firewall/filter.v6.d"
    - path: "/etc/network/firewall/nat.v4.d"
    - path: "/etc/network/firewall/nat.v6.d"
  loop_control:
    loop_var: directory
    label: "{{ directory.path }}"

- name: "Remove old Firewall files"
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: "absent"
  loop:
    - path: "/etc/network/firewall/filter.v4.d/0-default.v4"
    - path: "/etc/network/firewall/filter.v6.d/0-default.v6"
    - path: "/etc/network/firewall/nat.v4.d/0-default.v4"
    - path: "/etc/network/firewall/nat.v6.d/0-default.v6"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"

- name: "Configure Firewall Scripts"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    owner: "{{ template.owner | default('root') }}"
    group: "{{ template.group | default('root') }}"
    mode: "{{ template.mode | default('0600') }}"
  with_items:
    - src: "systemd/firewall.service.j2"
      dest: "/etc/systemd/system/firewall.service"
      mode: "0644"
    - src: "firewall/env.sh.j2"
      dest: "/etc/network/firewall/env.sh"
      mode: "0750"

    - src: "firewall/filter.v4.d/00-default.v4.j2"
      dest: "/etc/network/firewall/filter.v4.d/00-default.v4"

    - src: "firewall/filter.v4.d/10-default.v4.j2"
      dest: "/etc/network/firewall/filter.v4.d/10-default.v4"

    - src: "firewall/filter.v4.d/99-default.v4.j2"
      dest: "/etc/network/firewall/filter.v4.d/99-default.v4"

    - src: "firewall/nat.v4.d/00-default.v4.j2"
      dest: "/etc/network/firewall/nat.v4.d/00-default.v4"

    - src: "firewall/nat.v4.d/99-default.v4.j2"
      dest: "/etc/network/firewall/nat.v4.d/99-default.v4"

    - src: "firewall/filter.v6.d/00-default.v6.j2"
      dest: "/etc/network/firewall/filter.v6.d/00-default.v6"

    - src: "firewall/filter.v6.d/10-default.v6.j2"
      dest: "/etc/network/firewall/filter.v6.d/10-default.v6"

    - src: "firewall/filter.v6.d/99-default.v6.j2"
      dest: "/etc/network/firewall/filter.v6.d/99-default.v6"

    - src: "firewall/nat.v6.d/00-default.v6.j2"
      dest: "/etc/network/firewall/nat.v6.d/00-default.v6"

    - src: "firewall/nat.v6.d/99-default.v6.j2"
      dest: "/etc/network/firewall/nat.v6.d/99-default.v6"
  loop_control:
    loop_var: template
    label: "{{ template.src }}"
  notify: "Restart Firewall"

- name: "Enable Firewall Service"
  ignore_errors: "{{ inventory.id is not defined }}"
  ansible.builtin.systemd:
    name: "firewall.service"
    state: "started"
    daemon_reload: true
    enabled: true
