# Manage SSH
---
- name: "Create Run Directory"
  ansible.builtin.file:
    path: "/run/sshd"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Configure SSH"
  ansible.builtin.lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: "/usr/sbin/sshd -t -f %s"
  loop:
    - file: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - file: "/etc/ssh/sshd_config"
      regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    - file: "/etc/ssh/sshd_config"
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - file: "/etc/ssh/sshd_config"
      regexp: "^Port"
      line: "Port {{ acoby_ssh_port }}"
  notify: "Restart SSH"
  register: sshconfig

- name: "Allow root logins from backup hosts"
  ansible.builtin.blockinfile:
    dest: "/etc/ssh/sshd_config"
    marker: "# {mark}: Allow root logins from backup hosts (managed by ansible)."
    content: |
      {% for host in groups['backup'] %}
      Match Address {{ host }},{{ hostvars[host].network.pan.fqdn }},{{ hostvars[host].network.pan.ipv4.address }},{{ hostvars[host].network.pan.ipv6.address }}
          PermitRootLogin prohibit-password
      {% endfor %}
    validate: "/usr/sbin/sshd -t -f %s"
  notify: "Restart SSH"
  when:
    - "inventory.backup is defined"
    - "'backup' in group_names"

- name: "Reload SSH Service"
  ansible.builtin.service:
    name: "sshd"
    state: "reloaded"
    enabled: true
  ignore_errors: "{{ inventory.id is not defined }}"
  when: "sshconfig.changed"

- name: "Change SSH Port for Ansible Session"
  ansible.builtin.set_fact:
    ansible_port: "{{ acoby_ssh_port }}"
