---
- name: "Verify Mandatory fields"
  ansible.builtin.assert:
    that:
      - "acoby_ssh_port is defined"
      - "acoby_pan_port is defined"
      - "hardware is defined"
      - "hardware.type is defined"
      - "'virtual' in hardware.type or 'physical' in hardware.type"
      - "infrastructure is defined"
      - "infrastructure.os is defined"
      - "infrastructure.hostType is defined"
      - "infrastructure.type is defined"
      - "infrastructure.location is defined"
      - "infrastructure.provider is defined"
      - "infrastructure.provider.type is defined"
      - "owner is defined"
      - "owner.customerId is defined"
      - "network is defined"
      - "network.wan is defined"
      - "network.wan.fqdn is defined"
      - "network.wan.interface is defined"
      - "network.pan is defined"
      - "network.pan.fqdn is defined"
      - "network.pan.interface is defined"
      - "network.pan.private_key is defined"
      - "network.pan.public_key is defined"
      - "network.pan.ipv4 is defined"
      - "network.pan.ipv4.address is defined"
      - "network.pan.ipv4.netmask is defined"
      - "network.pan.ipv6 is defined"
      - "network.pan.ipv6.address is defined"
      - "network.pan.ipv6.prefix is defined"
      - "customers is defined"
      - "inventory_user is defined"
      - "inventory_pass is defined"
      - "inventory is defined"
      - "inventory.root_password is defined"
      - "inventory.mail is defined"
      - "inventory.network is defined"
      - "inventory.network.pan is defined"
      - "inventory.network.pan.domain is defined"
      - "inventory.network.pan.ipv4 is defined"
      - "inventory.network.pan.ipv6 is defined"
      - "users is defined"
      - "users | length > 0"
    fail_msg: "At least one value in the inventory is not defined"
  tags:
    - common

- name: "Install Common Necessary Debian Packages"
  ansible.builtin.include_tasks: configure_packages.yml
  args:
    apply:
      become: true
      tags:
        - common
        - packages
  tags:
    - common
    - packages

- name: "Configure root User"
  ansible.builtin.include_tasks: configure_root.yml
  args:
    apply:
      become: true
      tags:
        - common
        - root
  tags:
    - common
    - root

- name: "Configure provider specific settings"
  ansible.builtin.include_tasks: "{{ infrastructure.provider.type }}/main.yml"
  args:
    apply:
      become: true
      tags:
        - common
        - provider
  tags:
    - common
    - provider

- name: "Configure Users"
  ansible.builtin.include_tasks: configure_users.yml
  args:
    apply:
      become: true
      tags:
        - common
        - users
  when:
    - "owner.users is defined"
  loop: "{{ owner.users | default([]) }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
  tags:
    - common
    - users

- name: "Install Journald"
  ansible.builtin.include_tasks: configure_journald.yml
  args:
    apply:
      become: true
      tags:
        - common
        - journald
  tags:
    - common
    - journald

- name: "Configure MSMTP"
  ansible.builtin.include_tasks: configure_msmtp.yml
  args:
    apply:
      become: true
      tags:
        - common
        - mta
  when:
    - "'mailgateway' in groups"
    - "inventory_hostname not in groups['mailgateway']"
  tags:
    - common
    - mta

- name: "Configure Fail2Ban"
  ansible.builtin.include_tasks: configure_fail2ban.yml
  args:
    apply:
      become: true
      tags:
        - common
        - fail2ban
  tags:
    - common
    - fail2ban

- name: "Configure SSH"
  ansible.builtin.include_tasks: configure_ssh.yml
  args:
    apply:
      become: true
      tags:
        - common
        - ssh
  tags:
    - common
    - ssh

- name: "Install Private Area Network"
  ansible.builtin.include_tasks: wireguard/main.yml
  args:
    apply:
      become: true
      tags:
        - common
        - wireguard
        - pan
  tags:
    - common
    - wireguard
    - pan

- name: "Install Firewall"
  ansible.builtin.include_tasks: configure_firewall.yml
  args:
    apply:
      become: true
      tags:
        - common
        - firewall
  when:
    - "hardware.type is not defined or hardware.type != 'physical'"
  tags:
    - common
    - firewall

- name: "Install Icinga"
  ansible.builtin.include_tasks: configure_icinga.yml
  args:
    apply:
      become: true
      tags:
        - common
        - icinga

- name: "Install Icinga Satellite"
  ansible.builtin.include_tasks: icinga_satellite/main.yml
  args:
    apply:
      become: true
      tags:
        - common
        - icinga
        - icinga_satellite
  when:
    - "inventory.monitoring is defined"
    - "inventory.monitoring.master is defined"
  tags:
    - common
    - icinga
    - icinga_satellite

- name: "Install Icinga Agent"
  ansible.builtin.include_tasks: icinga_agent/main.yml
  args:
    apply:
      become: true
      tags:
        - common
        - icinga
        - icinga_agent
  when:
    - "inventory.monitoring is not defined or inventory.monitoring.master is not defined"
  tags:
    - common
    - icinga
    - icinga_agent

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - common
