---
- name: "Configure GlusterFS Client"
  ansible.builtin.include_tasks: "configure.yml"
  args:
    apply:
      become: true
      tags:
        - gfs_client
  when:
    - "'gluster' in groups"
    - "groups['gluster'] | length > 0"
  tags:
    - gfs_client
