---
- name: "Define some facts"
  ansible.builtin.set_fact:
    nfs_server: "{{ groups['nfs'] | sort | first }}"

- name: "Install NFS client"
  ansible.builtin.apt:
    name: "{{ default_nfs_client_packages }}"
    state: present

- name: "Add NFS Mount Point to /etc/fstab"
  ansible.posix.mount:
    src: "{{ hostvars[nfs_server].network.pan.fqdn }}:{{ nfs_share.path }}"
    path: "{{ nfs_share.mountpoint }}"
    fstype: "nfs4"
    opts: "rw,nosuid,intr,noatime,noauto,_netdev,vers=4.2,x-systemd.automount,x-systemd.requires=wg-quick@{{ network.pan.interface }}.service"
    state: "mounted"
  loop: "{{ hostvars[nfs_server].exports | default([]) }}"
  loop_control:
    loop_var: nfs_share
  when:
    - "nfs_server is defined"
    - "nfs_share.name not in disable_nfs_share | default([])"
    - "nfs_share.mountpoint is defined"
    - "infrastructure.storage is not defined or infrastructure.storage.nfs is not defined or not infrastructure.storage.nfs"

- name: "Check if RPCBind Service Exists"
  ansible.builtin.stat:
    path: "/etc/init.d/rpcbind"
  register: rpcbind_service_status

- name: "Stop RPC Bind"
  when:
    - "rpcbind_service_status.stat.exists"
  block:
    - name: "Stop RPC Bind Init Service"
      ansible.builtin.systemd:
        name: rpcbind
        state: stopped
        enabled: false
    - name: "Stop RPC Bind Socket Init Service"
      ansible.builtin.systemd:
        name: rpcbind.socket
        state: stopped
        enabled: false
