---
- name: "Configure NFS Client"
  ansible.builtin.include_tasks: configure.yml
  args:
    apply:
      become: true
      tags:
        - nfs_client
  when:
    - "'nfs' in groups"
    - "groups['nfs'] | length > 0"
  tags:
    - nfs_client
