---
- name: "Configure WireGate Bind of Network {{ network.name + '/' + network.address.interface }}"
  ansible.builtin.set_fact:
    wireguard_interface: "{{ network.address.interface }}"
    bind_config_path: "{{ bind_default.path }}/{{ network.address.interface }}"
  tags:
    - bind

- name: "Create directories for WireGate Bind of Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.file:
    path: "{{ directory.path }}"
    owner: "{{ directory.owner | default('root') }}"
    group: "{{ directory.group | default('root') }}"
    mode: "{{ directory.mode | default('0700') }}"
    state: "directory"
  loop:
    - path: "{{ bind_config_path }}"
      owner: "root"
      group: "bind"
      mode: "0755"
    - path: "/var/cache/bind/{{ wireguard_interface }}"
      owner: "root"
      group: "bind"
      mode: "0775"
  loop_control:
    loop_var: directory
    label: "{{ directory.path }}"
  tags:
    - bind

- name: "Check bind serial cache of Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.stat:
    path: "{{ bind_config_path }}/serial"
  register: _bind_serial_cache
  tags:
    - bind

- name: "Write bind serial to cache for Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.copy:
    content: "1"
    dest: "{{ bind_config_path }}/serial"
    owner: "root"
    group: "root"
    mode: "0400"
  when: "not _bind_serial_cache.stat.exists"
  tags:
    - bind

- name: "Read bind serial from cache of Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.command: "cat {{ bind_config_path }}/serial"
  register: _bind_serial_register
  changed_when: false

- name: "Increment Bind serial of Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.set_fact:
    bind_serial: "{{ _bind_serial_register.stdout | int + 1 }}"
  tags:
    - bind

- name: "Configure Bind Options for Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    owner: "{{ template.owner | default('root') }}"
    group: "{{ template.group | default('root') }}"
    mode: "{{ template.mode | default('0644') }}"
  with_items:
    - src: "named.conf.j2"
      dest: "{{ bind_config_path }}/named.conf"
      group: "bind"
    - src: "named.conf.options.j2"
      dest: "{{ bind_config_path }}/named.conf.options"
      group: "bind"
    - src: "named.conf.local.j2"
      dest: "{{ bind_config_path }}/named.conf.local"
      group: "bind"
    - src: "db.domain.j2"
      dest: "{{ bind_config_path }}/db.{{ network.domain }}"
      group: "bind"
    - src: "db.domain.rev.ipv4.j2"
      dest: "{{ bind_config_path }}/db.{{ network.domain }}.rev.ipv4"
      group: "bind"
    - src: "db.domain.rev.ipv6.j2"
      dest: "{{ bind_config_path }}/db.{{ network.domain }}.rev.ipv6"
      group: "bind"
    - src: "named.defaults.j2"
      dest: "/etc/default/named_{{ wireguard_interface }}"
    - src: "named.service.j2"
      dest: "/lib/systemd/system/named_{{ wireguard_interface }}.service"
  loop_control:
    loop_var: template
  register: _bind_templates
  tags:
    - bind

- name: "Write bind serial to cache for Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.copy:
    content: "{{ bind_serial }}"
    dest: "{{ bind_config_path }}/serial"
    owner: "root"
    group: "root"
    mode: "0400"
  tags:
    - bind

- name: "Enable Bind service for Network {{ network.name + '/' + wireguard_interface }}"
  ansible.builtin.systemd:
    name: "named_{{ wireguard_interface }}"
    state: "started"
    daemon_reload: true
    enabled: true
  register: bind_service
  tags:
    - bind

- name: "Restart Bind service for network {{ network.name + '/' + network.address.interface }}"
  ansible.builtin.systemd:
    name: "named_{{ wireguard_interface }}"
    state: "restarted"
  when:
    - "_bind_templates.changed"
    - "not bind_service.changed"
  tags:
    - bind
