---
dependencies:
  - role: acoby.collection.common

galaxy_info:
  author: Thoralf Rickert-Wendt
  description: A common role for all system
  company: Acoby GmbH
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - cloud
    - system
