---
- name: "Create network directory structure"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - path: "/etc/network"
    - path: "/etc/cloud/cloud.cfg.d"

- name: "Configure Hetzner Cloud Environment"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    owner: "{{ template.owner | default('root') }}"
    group: "{{ template.group | default('root') }}"
    mode: "{{ template.mode | default('0644') }}"
    backup: "{{ template.backup | default(omit) }}"
  loop:
    - src: "{{ infrastructure.provider.type }}/cloud/cloud.cfg.d/99-acoby-ansible-managed.cfg"
      dest: "/etc/cloud/cloud.cfg.d/99-acoby-ansible-managed.cfg"
    - src: "{{ infrastructure.provider.type }}/resolv.conf.j2"
      dest: "/etc/resolv.conf"
    - src: "{{ infrastructure.provider.type }}/network/interfaces.j2"
      dest: "/etc/network/interfaces"
      backup: true
  loop_control:
    loop_var: template
    label: "{{ template.src }}"
  ignore_errors: "{{ inventory.id is not defined }}"
  register: _configure_interfaces

- name: "Reboot necessary"
  ansible.builtin.reboot:
    msg: "Networking changes found, rebooting"
  when:
    - "_configure_interfaces is changed"
    - "reboot_when_required | bool"
